services:
  web:
    build: .
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - .env
    depends_on:
      - db_pg
    restart: always
    networks:
      - django_net

  db_pg:
    image: postgres:16
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
    restart: always
    networks:
      - django_net

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - static_volume:/app/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always
    networks:
      - django_net

volumes:
  pg_data:
  static_volume:

networks:
  django_net:
